### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by janbbeck**
Just a few text corrections.
Open issues:

Previously, we deleted 'proxy server'. Should it say 'server' here?

Capitalization. I would propose that we always capitalize SSH-MITM unless as part of a command. Agreed?

### CODE REVIEW

**Comment by manfred-kaiser** [comment]
> Previously, we deleted 'proxy server'. Should it say 'server' here?

:+1: yes

> Capitalization. I would propose that we always capitalize SSH-MITM unless as part of a command. Agreed?

:+1: Yes

**Comment by janbbeck** [comment]
So, just so we are on the same page:

```'title': 'SSH-MITM SERVER & content inspection',```

```'title': 'SSH-MITM is open source',```

```'install.html': 'SSH-MITM server is easy to install with Python and PIP',```



`SSH-MITM server` in all 3 cases?

**Comment by manfred-kaiser** [comment]
> `'title': 'SSH-MITM SERVER & content inspection',`

We should rewrite this, because this does not make sense.
The problem is, that I used this slogan on the main page too. https://www.ssh-mitm.at

What do you think about "**SSH-MITM - content inspection for ssh**"


> `'title': 'SSH-MITM is open source',`

This is ok


> `'install.html': 'SSH-MITM server is easy to install with Python and PIP',`

'server' should be removed

**Comment by janbbeck** [comment]
> > `'title': 'SSH-MITM SERVER & content inspection',`
> 
> We should rewrite this, because this does not make sense.
> The problem is, that I used this slogan on the main page too. https://www.ssh-mitm.at
> 
> What do you think about "**SSH-MITM - content inspection for ssh**"
> 

I think it goes further than just content inspection. How about
SSH-MITM - content inspection and vulnerability analysis for ssh

**Comment by manfred-kaiser** [comment]
What about:

SSH-MITM - ssh audits made simple

**Comment by janbbeck** [comment]
> What about:
> 
> SSH-MITM - ssh audits made simple
> 
> Perhaps not good, because both parts start with ssh disappointed

Awesome. I like it.

**Comment by manfred-kaiser** [comment]
I know the tool can be used for other (malicious) things but the intended use case are audits.

I want to avoid to be associated with illegal things...

> > What about:
> > SSH-MITM - ssh audits made simple
> > Perhaps not good, because both parts start with ssh disappointed
> 
> Awesome. I like it.

:+1: :smiley:

**Comment by janbbeck** [comment]
Ok, I think all the changes are in. Please check

**Comment by manfred-kaiser** [comment]
I will merge them at home. I want to update the main website to match the slogan and other things.

**Review by manfred-kaiser — APPROVED** [review]

**Pull request merged**
